### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by spoenemann** [axfrank/ultimate-graphframework-comparison#2]
Running `npm run start` leads to

```
[11:34:43] Using gulpfile ~/github/ultimate-graphframework-comparison/gulpfile.js
[11:34:43] Starting 'default'...
[11:34:43] Starting 'build-data'...
[11:34:43] Starting 'versioninfo'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Command failed: sed -i "s/§§date§§/2017-07-21/" ./app/VersionInformation.ts
sed: 1: "./app/VersionInformatio ...": invalid command code .

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

Using Mac OS 10.12.5 and npm 4.6.1

**Comment by koppor** [comment]
Thank you for your report. Could you please file it against our BASE repository at https://github.com/ultimate-comparisons/ultimate-comparison-BASE/issues?

Would it be possible that you also try whether our [BASE version](https://github.com/ultimate-comparisons/ultimate-comparison-BASE) works? (I think, it won't. But just to be sure).

We know, it doesn't work on windows (see https://github.com/ultimate-comparisons/ultimate-comparison-BASE/issues/12), but that is a different issue.

**Comment by koppor** [comment]
We searched stackoverflow, found https://stackoverflow.com/a/14813278/873282 and applied it to the master branch.

Could you try the latest version? We don't have a Mac OS X here.

**Comment by spoenemann** [comment]
Now gradlew fails complaining that it doesn't find a task `run`. If I replace the task name with `md2json` in [line 112 of gulpfile.js](https://github.com/ultimate-comparisons/ultimate-graphframework-comparison/blob/252481a3125c285d62aa8315b82db5cfcf41f2cc/gulpfile.js#L112), I get the following output:

```
[15:02:43] Using gulpfile ~/github/ultimate-graphframework-comparison/gulpfile.js
[15:02:43] Starting 'default'...
[15:02:43] Starting 'build-data'...
[15:02:43] Starting 'versioninfo'...
[15:02:43] Finished 'versioninfo' after 112 ms
[15:02:43] Starting 'determinecolors'...
[15:02:43] Finished 'determinecolors' after 248 μs
[15:02:43] Starting 'markdown'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Command failed: ./gradlew -q -b ./app/java/md-to-json/build.gradle md2json -PappArgs="[$/
# D3 - https://d3js.org/

## Drag & Drop
- Manually

## Angular2 Support
- No

## Straight Line
- Yes

## Label On Line
- Yes

## Arrow Heads
- Manually

## Scaling
- Manually

## Rendering Method
- Canvas

## Different Edge Types
- Yes

## Explicit Data Model
- No

## Docking Points
- No

## Connection Types
- Other

## Performance
- Slow
/$, 1, true]"
Exception in thread "main" java.lang.NumberFormatException: For input string: " 1"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.parseInt(Integer.java:615)
        at md2json.Md2Json.main(Md2Json.java:25)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':md2json'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by koppor** [comment]
I was in a hurry and accidently a WIP commit to `master`. Could you please retry? 😇

**Comment by spoenemann** [comment]
Works now, thanks.
